#networks:
#  ragflow:
#    driver: bridge

#volumes:
#  esdata01:
#    driver: local
#  infinity_data:
#    driver: local
#  mysql_data:
#    driver: local
#  minio_data:
#    driver: local
#  redis_data:
#    driver: local

volumes:  # using external volumes defined somewhere else and already created
  ragflow_esdata01:
    external: true
  ragflow_mysql_data:
    external: true
  ragflow_minio_data:
    external: true
  ragflow_redis_data:
    external: true

services:

  elasticsearch:
#    container_name: ragflow-es-01
    profiles:
      - elasticsearch  # see DOC_ENGINE in .env
    image: elasticsearch:${STACK_VERSION}
    volumes:
#      - esdata01:/usr/share/elasticsearch/data
      - ragflow_esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    env_file: .env
    environment:
      - node.name=es01
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.watermark.low=5gb
      - cluster.routing.allocation.disk.watermark.high=3gb
      - cluster.routing.allocation.disk.watermark.flood_stage=2gb
      - TZ=${TIMEZONE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
#    networks:
#      - ragflow
    restart: unless-stopped

  mysql:
    # mysql:5.7 linux/arm64 image is unavailable.
    image: mysql:8.0.39
#    container_name: ragflow-mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
      --init-file /data/application/init.sql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
#      - mysql_data:/var/lib/mysql
      - ragflow_mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
#    networks:
#      - ragflow
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
#    container_name: ragflow-minio
    command: server --console-address ":9001" /data
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
#      - minio_data:/data
      - ragflow_minio_data:/data
#    networks:
#      - ragflow
    restart: unless-stopped

  redis:
    # swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/valkey/valkey:8
    image: valkey/valkey:8
#    container_name: ragflow-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
    env_file: .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
#      - redis_data:/data
      - ragflow_redis_data:/data
#    networks:
#      - ragflow
    restart: unless-stopped

  server:
    profiles:
      - production
    depends_on:
      mysql:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
#    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 81:80
      - 444:443
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - type: bind
        source: ../web/dist
        target: /ragflow/web/dist
      - type: bind
        source: ../api
        target: /ragflow/api
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - WS=4  # spawn multi worker processes
#    networks:
#      - ragflow
    restart: unless-stopped
    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
    extra_hosts:
      - "host.docker.internal:host-gateway"
